name: Scoping Issue
description: Use this template to outline the scope of a new project or feature.
title: "[SCOPE] "
labels: ["scope"]
projects: []
assignees:
  - melithom
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!