name: Scoping Issue
description: Use this template to outline the scope of a new project or feature.
title: "[SCOPE] "
labels: ["scope"]
projects: []
assignees:
  - melithom

body:
  - type: markdown
    attributes:
      value: |
        ## Project/Feature Overview
        Provide a brief description of the project or feature. 