# Workflow for continuous integration

name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 60 seconds
      run: sleep 60s
      shell: bash