name: Matrix fun

on:
  workflow_dispatch:
    inputs:
      runA:
        description: 'A?'
        required: true
        default: true
        type: boolean
      runB:
        description: 'B?'
        required: true
        default: true
        type: boolean
      runC:
        description: 'C?'
        required: true
        default: true
        type: boolean
      run1:
        description: '1?'
        required: true
        default: true
        type: boolean
      run2:
        description: '2?'
        required: true
        default: true
        type: boolean
      run3:
        description: '3?'
        required: true
        default: true
        type: boolean
        
jobs:
  jobby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        letters: [ a, b, c ]
        numbers: [ 1, 2, 3 ]
    
    steps:
      - run: echo ${{ matrix.letters }} ${{ matrix.numers }}
        if: ${{ (github.event.inputs.runA && matrix.letters=="a") || (github.event.inputs.runB && matrix.letters=="b") || (github.event.inputs.runC && matrix.letters=="c") && (github.event.inputs.run1 && matrix.numbers=="1") || (github.event.inputs.run2 && matrix.numbers=="2") || (github.event.inputs.run3 && matrix.numbers=="3") }}
